### ISSUE TITLE
Readability-like function

### ISSUE THREAD

**Issue by chenhunghan** [HIIT/dime-webextension#8]
At dime-webextension version 0.3, we are using [readability.js lib](https://www.npmjs.com/package/readability-js) to get main text content from web page. It works as expected but the library itself is over 4MB and there is a size limitation of webextension on Firefox. We are thinking two solutions on this issue.
1. Find a workaround for the size limit. 
2. Using lighter readability-like libs.

I haven't check solution one. It should be have higher priority. However, for solution two, there are some interesting articles on designing algorithms for this purpose. Christian Kohlschütter gived a brief answer on a [question](http://stackoverflow.com/questions/3652657/what-algorithm-does-readability-use-for-extracting-text-from-urls) on Stackoverflow. His paper "[Boilerplate Detection using Shallow Text Features](Boilerplate Detection using Shallow Text Features)" should help algorithm design.

Apart from research, there are serveral heuristics solutions. The first of it's kinds seems to be written in Javascript in 2009 by Arc90 Inc. The [source code](https://github.com/mozilla/readability) is managed by Mozilla or could be find on [Google Code Archive](https://code.google.com/archive/p/arc90labs-readability/downloads). The [Safari Reader](http://blog.manbolo.com/2013/03/18/safari-reader-source-code) is based on Readability (See [the analysis of design](https://mathiasbynens.be/notes/safari-reader))

**Comment by chenhunghan** [comment]
It seems like there is no workaround for the size limit. The limit exists because the source code has to pass the validation of [mozilla/addons-linter](https://github.com/mozilla/addons-linter). The addons-linter has 4MB limits, see the [discussion](https://github.com/mozilla/addons/issues/181) here. We should start consider to implement our own readability-like function.

**Comment by chenhunghan** [comment]
This is resolved in https://github.com/HIIT/dime-webextension/commit/360dbc33c4899b7b22eef5a16fc7e5f6a83b5912

**Comment by nnn-gif** [comment]
@chenhunghan still getting 4mb limit error
